# Data Ingestion

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('sales_review.Xls')
df.head(10)

,التاريخ,الوقت,الرقم,الاسم,عدد الأصناف,اجمالي قبل الخصم,اجمالي الخصم,الضريبة,الاجمالي,المدفوع,الباقي,Unnamed: 11
0,2026-05-07 11:48:44.250,2026-05-07 11:48:44.250,19647.0,الحبيب,2.0,2900.0,0.0,0.0,2900.0,0.0,2900.0,NaN
1,2026-05-07 11:48:22.880,2026-05-07 11:48:22.880,19646.0,امازون ا/ مجدي,1.0,75.0,0.0,0.0,75.0,0.0,75.0,NaN
2,2026-05-07 11:48:08.697,2026-05-07 11:48:08.697,19645.0,رمضان العالمية,1.0,1300.0,0.0,0.0,1300.0,0.0,1300.0,NaN
3,2026-05-07 11:46:00.113,2026-05-07 11:46:00.113,19644.0,سامح الشرقية,1.0,3800.0,0.0,0.0,3800.0,3800.0,0.0,NaN
4,2026-05-07 11:38:09.710,2026-05-07 11:38:09.710,19643.0,تعامل نقدي,5.0,14600.0,0.0,0.0,14600.0,14600.0,0.0,NaN
5,2026-05-07 11:36:49.903,2026-05-07 11:36:49.903,19642.0,الامان ا/ حسام,2.0,1100.0,0.0,0.0,1100.0,0.0,1100.0,NaN
6,2026-05-07 11:36:25.347,2026-05-07 11:36:25.347,19641.0,احمد جميل,13.0,9730.0,0.0,0.0,9730.0,0.0,9730.0,NaN
7,2026-05-07 11:34:49.313,2026-05-07 11:34:49.313,19640.0,ضياء عفيفي,1.0,425.0,0.0,0.0,425.0,0.0,425.0,NaN
8,2026-05-07 11:34:36.307,2026-05-07 11:34:36.307,19639.0,د/ محمد المودة,1.0,480.0,0.0,0.0,480.0,0.0,480.0,NaN
9,2026-05-07 11:33:54.927,2026-05-07 11:33:54.927,19638.0,د/ محمد المودة,1.0,960.0,0.0,0.0,960.0,0.0,960.0,NaN

# Data Processing & Cleaning

## -Data cleaning

In [4]:
df = df.drop(columns=['Unnamed: 11'])
df.head(10)

,التاريخ,الوقت,الرقم,الاسم,عدد الأصناف,اجمالي قبل الخصم,اجمالي الخصم,الضريبة,الاجمالي,المدفوع,الباقي
0,2026-05-07 11:48:44.250,2026-05-07 11:48:44.250,19647.0,الحبيب,2.0,2900.0,0.0,0.0,2900.0,0.0,2900.0
1,2026-05-07 11:48:22.880,2026-05-07 11:48:22.880,19646.0,امازون ا/ مجدي,1.0,75.0,0.0,0.0,75.0,0.0,75.0
2,2026-05-07 11:48:08.697,2026-05-07 11:48:08.697,19645.0,رمضان العالمية,1.0,1300.0,0.0,0.0,1300.0,0.0,1300.0
3,2026-05-07 11:46:00.113,2026-05-07 11:46:00.113,19644.0,سامح الشرقية,1.0,3800.0,0.0,0.0,3800.0,3800.0,0.0
4,2026-05-07 11:38:09.710,2026-05-07 11:38:09.710,19643.0,تعامل نقدي,5.0,14600.0,0.0,0.0,14600.0,14600.0,0.0
5,2026-05-07 11:36:49.903,2026-05-07 11:36:49.903,19642.0,الامان ا/ حسام,2.0,1100.0,0.0,0.0,1100.0,0.0,1100.0
6,2026-05-07 11:36:25.347,2026-05-07 11:36:25.347,19641.0,احمد جميل,13.0,9730.0,0.0,0.0,9730.0,0.0,9730.0
7,2026-05-07 11:34:49.313,2026-05-07 11:34:49.313,19640.0,ضياء عفيفي,1.0,425.0,0.0,0.0,425.0,0.0,425.0
8,2026-05-07 11:34:36.307,2026-05-07 11:34:36.307,19639.0,د/ محمد المودة,1.0,480.0,0.0,0.0,480.0,0.0,480.0
9,2026-05-07 11:33:54.927,2026-05-07 11:33:54.927,19638.0,د/ محمد المودة,1.0,960.0,0.0,0.0,960.0,0.0,960.0

In [5]:
df = df.rename(columns={
    'التاريخ': 'date',
    'الوقت': 'time',
    'الرقم': 'id',
    'الاسم': 'customer_name',
    'عدد الأصناف': 'items_count',
    'اجمالي قبل الخصم': 'total_before_discount',
    'اجمالي الخصم': 'discount_amount',
    'الضريبة': 'tax',
    'الاجمالي': 'total',
    'المدفوع': 'paid_amount',
    'الباقي': 'remaining_balance'
})

df.head()

,date,time,id,customer_name,items_count,total_before_discount,discount_amount,tax,total,paid_amount,remaining_balance
0,2026-05-07 11:48:44.250,2026-05-07 11:48:44.250,19647.0,الحبيب,2.0,2900.0,0.0,0.0,2900.0,0.0,2900.0
1,2026-05-07 11:48:22.880,2026-05-07 11:48:22.880,19646.0,امازون ا/ مجدي,1.0,75.0,0.0,0.0,75.0,0.0,75.0
2,2026-05-07 11:48:08.697,2026-05-07 11:48:08.697,19645.0,رمضان العالمية,1.0,1300.0,0.0,0.0,1300.0,0.0,1300.0
3,2026-05-07 11:46:00.113,2026-05-07 11:46:00.113,19644.0,سامح الشرقية,1.0,3800.0,0.0,0.0,3800.0,3800.0,0.0
4,2026-05-07 11:38:09.710,2026-05-07 11:38:09.710,19643.0,تعامل نقدي,5.0,14600.0,0.0,0.0,14600.0,14600.0,0.0

In [6]:
constant_columns = [col for col in df.columns if df[col].nunique() <= 1]

print("constant columns:", constant_columns)

df.drop(columns=constant_columns, inplace=True)
df.head(10)

constant columns: ['tax']

,date,time,id,customer_name,items_count,total_before_discount,discount_amount,total,paid_amount,remaining_balance
0,2026-05-07 11:48:44.250,2026-05-07 11:48:44.250,19647.0,الحبيب,2.0,2900.0,0.0,2900.0,0.0,2900.0
1,2026-05-07 11:48:22.880,2026-05-07 11:48:22.880,19646.0,امازون ا/ مجدي,1.0,75.0,0.0,75.0,0.0,75.0
2,2026-05-07 11:48:08.697,2026-05-07 11:48:08.697,19645.0,رمضان العالمية,1.0,1300.0,0.0,1300.0,0.0,1300.0
3,2026-05-07 11:46:00.113,2026-05-07 11:46:00.113,19644.0,سامح الشرقية,1.0,3800.0,0.0,3800.0,3800.0,0.0
4,2026-05-07 11:38:09.710,2026-05-07 11:38:09.710,19643.0,تعامل نقدي,5.0,14600.0,0.0,14600.0,14600.0,0.0
5,2026-05-07 11:36:49.903,2026-05-07 11:36:49.903,19642.0,الامان ا/ حسام,2.0,1100.0,0.0,1100.0,0.0,1100.0
6,2026-05-07 11:36:25.347,2026-05-07 11:36:25.347,19641.0,احمد جميل,13.0,9730.0,0.0,9730.0,0.0,9730.0
7,2026-05-07 11:34:49.313,2026-05-07 11:34:49.313,19640.0,ضياء عفيفي,1.0,425.0,0.0,425.0,0.0,425.0
8,2026-05-07 11:34:36.307,2026-05-07 11:34:36.307,19639.0,د/ محمد المودة,1.0,480.0,0.0,480.0,0.0,480.0
9,2026-05-07 11:33:54.927,2026-05-07 11:33:54.927,19638.0,د/ محمد المودة,1.0,960.0,0.0,960.0,0.0,960.0

In [7]:
df.isnull().sum()

date                     1
time                     1
id                       1
customer_name            1
items_count              1
total_before_discount    1
discount_amount          1
total                    1
paid_amount              1
remaining_balance        1
dtype: int64

In [8]:
df.tail()

,date,time,id,customer_name,items_count,total_before_discount,discount_amount,total,paid_amount,remaining_balance
19583,2025-07-15 17:45:38.577,2025-07-15 17:45:38.577,4.0,ابراهيم فيصل,12.0,31310.0,0.0,31310.0,31310.0,0.0
19584,2025-07-15 17:32:36.150,2025-07-15 17:32:36.150,3.0,شركة كوين ا/ عبير,4.0,3345.0,0.0,3345.0,3345.0,0.0
19585,2025-07-15 17:31:07.870,2025-07-15 17:31:07.870,2.0,الصاوي,1.0,525.0,0.0,525.0,525.0,0.0
19586,2025-07-15 17:30:50.567,2025-07-15 17:30:50.567,1.0,ابراهيم سوبر ماركت,1.0,1800.0,0.0,1800.0,1800.0,0.0
19587,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.dropna(how='all', inplace=True)
df.isnull().sum()

date                     0
time                     0
id                       0
customer_name            0
items_count              0
total_before_discount    0
discount_amount          0
total                    0
paid_amount              0
remaining_balance        0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

## -Data Validation

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19587 entries, 0 to 19586
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   19587 non-null  datetime64[ns]
 1   time                   19587 non-null  datetime64[ns]
 2   id                     19587 non-null  float64
 3   customer_name          19587 non-null  object
 4   items_count            19587 non-null  float64
 5   total_before_discount  19587 non-null  float64
 6   discount_amount        19587 non-null  float64
 7   total                  19587 non-null  float64
 8   paid_amount            19587 non-null  float64
 9   remaining_balance      19587 non-null  float64
dtypes: datetime64[ns](2), float64(7), object(1)
memory usage: 1.6+ MB

In [12]:
df['date'] = pd.to_datetime(df['date'])
df['id'] = df['id'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19587 entries, 0 to 19586
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   19587 non-null  datetime64[ns]
 1   time                   19587 non-null  datetime64[ns]
 2   id                     19587 non-null  int64
 3   customer_name          19587 non-null  object
 4   items_count            19587 non-null  float64
 5   total_before_discount  19587 non-null  float64
 6   discount_amount        19587 non-null  float64
 7   total                  19587 non-null  float64
 8   paid_amount            19587 non-null  float64
 9   remaining_balance      19587 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(1), object(1)
memory usage: 1.6+ MB

In [13]:
df['customer_name'] = df['customer_name'].str.strip()
df.head(10)

,date,time,id,customer_name,items_count,total_before_discount,discount_amount,total,paid_amount,remaining_balance
0,2026-05-07 11:48:44.250,2026-05-07 11:48:44.250,19647,الحبيب,2.0,2900.0,0.0,2900.0,0.0,2900.0
1,2026-05-07 11:48:22.880,2026-05-07 11:48:22.880,19646,امازون ا/ مجدي,1.0,75.0,0.0,75.0,0.0,75.0
2,2026-05-07 11:48:08.697,2026-05-07 11:48:08.697,19645,رمضان العالمية,1.0,1300.0,0.0,1300.0,0.0,1300.0
3,2026-05-07 11:46:00.113,2026-05-07 11:46:00.113,19644,سامح الشرقية,1.0,3800.0,0.0,3800.0,3800.0,0.0
4,2026-05-07 11:38:09.710,2026-05-07 11:38:09.710,19643,تعامل نقدي,5.0,14600.0,0.0,14600.0,14600.0,0.0
5,2026-05-07 11:36:49.903,2026-05-07 11:36:49.903,19642,الامان ا/ حسام,2.0,1100.0,0.0,1100.0,0.0,1100.0
6,2026-05-07 11:36:25.347,2026-05-07 11:36:25.347,19641,احمد جميل,13.0,9730.0,0.0,9730.0,0.0,9730.0
7,2026-05-07 11:34:49.313,2026-05-07 11:34:49.313,19640,ضياء عفيفي,1.0,425.0,0.0,425.0,0.0,425.0
8,2026-05-07 11:34:36.307,2026-05-07 11:34:36.307,19639,د/ محمد المودة,1.0,480.0,0.0,480.0,0.0,480.0
9,2026-05-07 11:33:54.927,2026-05-07 11:33:54.927,19638,د/ محمد المودة,1.0,960.0,0.0,960.0,0.0,960.0

## -Data Transformation

In [15]:
df['time'] = pd.to_datetime(df['time']).dt.strftime('%I:%M:%S %p')
df.head(10)

,date,time,id,customer_name,items_count,total_before_discount,discount_amount,total,paid_amount,remaining_balance
0,2026-05-07 11:48:44.250,11:48:44 AM,19647,الحبيب,2.0,2900.0,0.0,2900.0,0.0,2900.0
1,2026-05-07 11:48:22.880,11:48:22 AM,19646,امازون ا/ مجدي,1.0,75.0,0.0,75.0,0.0,75.0
2,2026-05-07 11:48:08.697,11:48:08 AM,19645,رمضان العالمية,1.0,1300.0,0.0,1300.0,0.0,1300.0
3,2026-05-07 11:46:00.113,11:46:00 AM,19644,سامح الشرقية,1.0,3800.0,0.0,3800.0,3800.0,0.0
4,2026-05-07 11:38:09.710,11:38:09 AM,19643,تعامل نقدي,5.0,14600.0,0.0,14600.0,14600.0,0.0
5,2026-05-07 11:36:49.903,11:36:49 AM,19642,الامان ا/ حسام,2.0,1100.0,0.0,1100.0,0.0,1100.0
6,2026-05-07 11:36:25.347,11:36:25 AM,19641,احمد جميل,13.0,9730.0,0.0,9730.0,0.0,9730.0
7,2026-05-07 11:34:49.313,11:34:49 AM,19640,ضياء عفيفي,1.0,425.0,0.0,425.0,0.0,425.0
8,2026-05-07 11:34:36.307,11:34:36 AM,19639,د/ محمد المودة,1.0,480.0,0.0,480.0,0.0,480.0
9,2026-05-07 11:33:54.927,11:33:54 AM,19638,د/ محمد المودة,1.0,960.0,0.0,960.0,0.0,960.0

In [16]:
df['date_time'] = pd.to_datetime(df['date'].astype(str) + ' ' + df['time'].astype(str))

df.drop(columns=['date', 'time'], inplace=True)

cols = ['date_time'] + [c for c in df.columns if c != 'date_time']
df = df[cols]
df.head(10)

C:\Users\Rahma Goda\AppData\Local\Temp\ipykernel_7284\440255457.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_time'] = pd.to_datetime(df['date'].astype(str) + ' ' + df['time'].astype(str))

,date_time,id,customer_name,items_count,total_before_discount,discount_amount,total,paid_amount,remaining_balance
0,2026-05-07 11:48:44,19647,الحبيب,2.0,2900.0,0.0,2900.0,0.0,2900.0
1,2026-05-07 11:48:22,19646,امازون ا/ مجدي,1.0,75.0,0.0,75.0,0.0,75.0
2,2026-05-07 11:48:08,19645,رمضان العالمية,1.0,1300.0,0.0,1300.0,0.0,1300.0
3,2026-05-07 11:46:00,19644,سامح الشرقية,1.0,3800.0,0.0,3800.0,3800.0,0.0
4,2026-05-07 11:38:09,19643,تعامل نقدي,5.0,14600.0,0.0,14600.0,14600.0,0.0
5,2026-05-07 11:36:49,19642,الامان ا/ حسام,2.0,1100.0,0.0,1100.0,0.0,1100.0
6,2026-05-07 11:36:25,19641,احمد جميل,13.0,9730.0,0.0,9730.0,0.0,9730.0
7,2026-05-07 11:34:49,19640,ضياء عفيفي,1.0,425.0,0.0,425.0,0.0,425.0
8,2026-05-07 11:34:36,19639,د/ محمد المودة,1.0,480.0,0.0,480.0,0.0,480.0
9,2026-05-07 11:33:54,19638,د/ محمد المودة,1.0,960.0,0.0,960.0,0.0,960.0

In [18]:
df['items_count'] = df['items_count'].astype(int)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19587 entries, 0 to 19586
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date_time              19587 non-null  datetime64[ns]
 1   id                     19587 non-null  int64
 2   customer_name          19587 non-null  object
 3   items_count            19587 non-null  int64
 4   total_before_discount  19587 non-null  float64
 5   discount_amount        19587 non-null  float64
 6   total                  19587 non-null  float64
 7   paid_amount            19587 non-null  float64
 8   remaining_balance      19587 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(1)
memory usage: 1.5+ MB

In [23]:
df.describe()

,date_time,id,items_count,total_before_discount,discount_amount,total,paid_amount,remaining_balance
count,19587,19587.000000,19587.000000,19587.000000,19587.000000,19587.000000,19587.000000,19587.000000
mean,2025-12-04 04:48:11.157451520,9808.938122,3.661663,6880.226010,8.851473,6871.374537,4855.616529,2015.741415
min,2025-07-15 17:30:50,1.000000,1.000000,5.000000,0.000000,5.000000,0.000000,-9712.000000
25%,2025-09-13 15:58:59.500000,4901.500000,1.000000,588.375000,0.000000,585.750000,0.000000,0.000000
50%,2025-12-06 19:13:30,9801.000000,2.000000,1668.000000,0.000000,1660.000000,750.000000,0.000000
75%,2026-02-15 12:29:05,14709.500000,4.000000,5625.000000,0.000000,5622.125000,3250.000000,300.000000
max,2026-05-07 11:48:44,19647.000000,31.000000,602627.000000,7200.000000,602627.000000,475390.000000,284250.000000
std,NaN,5669.928717,4.431403,17042.590337,130.120608,17015.721268,14379.086430,9254.842502

In [24]:
print(f"{df['date_time'].min()}\n{df['date_time'].max()}")

2025-07-15 17:30:50
2026-05-07 11:48:44

## -Feature Engineering

In [20]:
negative_totals = df[df['total'] < 0]
print(f"Number of rows with negative total: {len(negative_totals)}")

calculated_total = df['total_before_discount'] - df['discount_amount']
mismatched_billing = df[abs(df['total'] - calculated_total) > 0.1]
print(f"Number of invoices with billing mismatches: {len(mismatched_billing)}")

Number of rows with negative total: 0
Number of invoices with billing mismatches: 0

In [21]:
def check_payment_status(row):
    if row['remaining_balance'] == 0:
        return 'Paid'
    elif row['paid_amount'] == 0:
        return 'Unpaid'
    else:
        return 'Partially Paid'

df['payment_status'] = df.apply(check_payment_status, axis=1)

print("Payment status distribution:")
print(df['payment_status'].value_counts())

Payment status distribution:
payment_status
Paid              13972
Unpaid             5338
Partially Paid      277
Name: count, dtype: int64

# Load data to MySQL

In [ ]:
import urllib.parse
from sqlalchemy import create_engine

# MySQL Connection

db_username = "root"
raw_password = "1@RSB22d#"
db_host = "localhost"
db_port = "3306"
db_name = "medical_sales"

safe_password = urllib.parse.quote_plus(raw_password)

connection_url = (
    f"mysql+mysqlconnector://{db_username}:{safe_password}"
    f"@{db_host}:{db_port}/{db_name}"
)

engine = create_engine(connection_url)

# Upload Cleaned Data


df.to_sql(
    name="cleaned_sales",
    con=engine,
    if_exists="replace",
    index=False
)

print("Cleaned data uploaded successfully to MySQL.")

Cleaned data uploaded successfully to MySQL.

# Data Aggregation & Sales Performance Analysis

In [26]:
total_sales = df["total"].sum()
print("Total Sales:", total_sales)
total_discount = df["discount_amount"].sum()
print("Total Discount:", total_discount)
total_remaining = df["remaining_balance"].sum()
print("Total Remaining:", total_remaining)
total_customers = df["customer_name"].nunique()
print("Number of Customers:", total_customers)
customer_summary = (
    df.groupby("customer_name")
      .agg(
          Total_Orders=("id", "count"),
          Total_Items=("items_count", "sum"),
          Total_Sales=("total", "sum"),
          Total_Paid=("paid_amount", "sum"),
          Remaining_Balance=("remaining_balance", "sum")
      )
      .reset_index()
)

customer_summary.head()
df["YearMonth"] = df["date_time"].dt.to_period("M")

monthly_sales = (
    df.groupby("YearMonth")
      .agg(
          Total_Sales=("total", "sum"),
          Total_Paid=("paid_amount", "sum"),
          Total_Discount=("discount_amount", "sum"),
          Invoices=("id", "count")
      )
      .reset_index()
)

print(monthly_sales)

Total Sales: 134589613.052
Total Discount: 173373.81
Total Remaining: 39482327.104
Number of Customers: 926
   YearMonth   Total_Sales    Total_Paid  Total_Discount  Invoices
0    2025-07  1.094635e+07  9.771038e+06         5467.50      1902
1    2025-08  1.593775e+07  1.372752e+07        22909.53      2258
2    2025-09  1.134263e+07  9.614584e+06        15874.60      1674
3    2025-10  1.000103e+07  8.368579e+06        15672.85      1701
4    2025-11  1.081279e+07  8.306280e+06        17156.40      1813
5    2025-12  1.733935e+07  1.265795e+07        21478.63      2409
6    2026-01  1.432254e+07  1.013496e+07        14731.45      1988
7    2026-02  1.262921e+07  8.428584e+06        17858.05      1835
8    2026-03  1.406547e+07  8.539968e+06        13163.55      1741
9    2026-04  1.501124e+07  4.762161e+06        19013.25      1849
10   2026-05  2.181260e+06  7.953282e+05        10048.00       417

# Medical Sales Analysis Module

In [ ]:
"""
MEDICAL SALES DATA ANALYSIS - COMPLETE PYTHON MODULE
Author: Data Engineering Team
Role: Microsoft Data Engineer
Purpose: Comprehensive data analysis with functions for all analysis components
"""

import pandas as pd
import numpy as np
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# CLASS 1: DATA LOADER - Handles all data loading and initial processing
# =============================================================================

class DataLoader:
    """Load and prepare data for analysis"""

    def __init__(self, filepath):
        self.filepath = filepath
        self.df = None
        self.load_data()

    def load_data(self):
        """Load Excel data and perform initial processing"""
        try:
            self.df = pd.read_excel(self.filepath)
            print(f"✓ Data loaded: {len(self.df):,} records, {len(self.df.columns)} columns")
        except Exception as e:
            print(f"✗ Error loading data: {str(e)}")
            return False

        # Convert date_time
        self.df['date_time'] = pd.to_datetime(self.df['date_time'])

        # Extract temporal features
        self._extract_temporal_features()

        # Calculate derived metrics
        self._calculate_metrics()

        return True

    def _extract_temporal_features(self):
        """Extract date/time components"""
        self.df['year'] = self.df['date_time'].dt.year
        self.df['month'] = self.df['date_time'].dt.month
        self.df['month_name'] = self.df['date_time'].dt.strftime('%B')
        self.df['day'] = self.df['date_time'].dt.day
        self.df['quarter'] = self.df['date_time'].dt.quarter
        self.df['week'] = self.df['date_time'].dt.isocalendar().week
        self.df['day_of_week'] = self.df['date_time'].dt.day_name()
        self.df['hour'] = self.df['date_time'].dt.hour
        self.df['date_only'] = self.df['date_time'].dt.date

    def _calculate_metrics(self):
        """Calculate derived metrics"""
        self.df['discount_percentage'] = (
            self.df['discount_amount'] / self.df['total_before_discount'] * 100
        ).round(2)
        self.df['payment_rate'] = (
            self.df['paid_amount'] / self.df['total'] * 100
        ).round(2)
        self.df['has_outstanding'] = (self.df['remaining_balance'] > 0).astype(int)

    def get_data(self):
        """Return processed dataframe"""
        return self.df

# =============================================================================
# CLASS 2: REVENUE ANALYZER - Analyzes revenue metrics
# =============================================================================

class RevenueAnalyzer:
    """Analyze revenue-related metrics"""

    def __init__(self, df):
        self.df = df

    def get_summary(self):
        """Get comprehensive revenue summary"""
        summary = {
            'total_revenue': self.df['total'].sum(),
            'revenue_before_discount': self.df['total_before_discount'].sum(),
            'total_discounts': self.df['discount_amount'].sum(),
            'avg_transaction': self.df['total'].mean(),
            'median_transaction': self.df['total'].median(),
            'max_transaction': self.df['total'].max(),
            'min_transaction': self.df['total'].min(),
            'std_dev_transaction': self.df['total'].std(),
        }
        return summary

    def get_monthly_analysis(self):
        """Analyze revenue by month"""
        monthly = self.df.groupby(self.df['date_time'].dt.to_period('M')).agg({
            'total': ['sum', 'count', 'mean'],
            'paid_amount': 'sum',
            'remaining_balance': 'sum',
            'discount_amount': 'sum'
        }).reset_index()

        monthly['date_time'] = monthly['date_time'].astype(str)
        monthly.columns = ['Month', 'Revenue', 'Transactions', 'Avg Value',
                          'Collected', 'Outstanding', 'Discounts']
        monthly['Collection Rate %'] = (
            (monthly['Collected'] / (monthly['Collected'] + monthly['Outstanding']) * 100)
            .round(2)
        )
        return monthly.round(2)

    def get_by_day_of_week(self):
        """Analyze revenue by day of week"""
        dow_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        dow = self.df.groupby('day_of_week').agg({
            'total': ['sum', 'count', 'mean'],
            'items_count': 'mean'
        }).reset_index()
        dow.columns = ['Day', 'Revenue', 'Transactions', 'Avg Value', 'Avg Items']
        dow['Day'] = pd.Categorical(dow['Day'], categories=dow_order, ordered=True)
        return dow.sort_values('Day').round(2)

# =============================================================================
# CLASS 3: CUSTOMER ANALYZER - Analyzes customer metrics and segments
# =============================================================================

class CustomerAnalyzer:
    """Analyze customer-related metrics"""

    def __init__(self, df):
        self.df = df
        self.customer_data = None
        self._aggregate_customers()

    def _aggregate_customers(self):
        """Aggregate customer-level metrics"""
        self.customer_data = self.df.groupby('customer_name').agg({
            'total': ['sum', 'count', 'mean', 'std'],
            'paid_amount': 'sum',
            'remaining_balance': 'sum',
            'date_time': ['min', 'max'],
            'items_count': 'mean'
        }).reset_index()

        self.customer_data.columns = [
            'customer', 'lifetime_value', 'transactions', 'avg_transaction',
            'std_transaction', 'total_paid', 'outstanding', 'first_purchase',
            'last_purchase', 'avg_items'
        ]

        self.customer_data['collection_rate'] = (
            self.customer_data['total_paid'] /
            (self.customer_data['total_paid'] + self.customer_data['outstanding']) * 100
        ).round(2)

    def segment_customers(self):
        """Segment customers by value"""
        q75 = self.customer_data['lifetime_value'].quantile(0.75)
        q50 = self.customer_data['lifetime_value'].quantile(0.50)

        def segment(value):
            if value >= q75:
                return 'High-Value'
            elif value >= q50:
                return 'Medium-Value'
            else:
                return 'Low-Value'

        self.customer_data['segment'] = self.customer_data['lifetime_value'].apply(segment)
        return self.customer_data.sort_values('lifetime_value', ascending=False)

    def get_top_customers(self, n=50):
        """Get top N customers by revenue"""
        return self.customer_data.nlargest(n, 'lifetime_value')

    def get_segment_summary(self):
        """Summary by customer segment"""
        segmented = self.segment_customers()
        summary = segmented.groupby('segment').agg({
            'customer': 'count',
            'lifetime_value': ['sum', 'mean'],
            'transactions': 'mean',
            'collection_rate': 'mean',
            'outstanding': 'sum'
        }).reset_index()

        summary.columns = [
            'Segment', 'Customer Count', 'Total Revenue', 'Avg Revenue',
            'Avg Transactions', 'Avg Collection Rate %', 'Total Outstanding'
        ]
        return summary.round(2)

# =============================================================================
# CLASS 4: PAYMENT ANALYZER - Analyzes payment and collection metrics
# =============================================================================

class PaymentAnalyzer:
    """Analyze payment and collection metrics"""

    def __init__(self, df):
        self.df = df

    def get_payment_status(self):
        """Analyze payment status distribution"""
        status_data = []

        for status, condition in [
            ('Fully Paid', self.df['remaining_balance'] == 0),
            ('Partially Paid', (self.df['remaining_balance'] > 0) & (self.df['paid_amount'] > 0)),
            ('Unpaid', self.df['paid_amount'] == 0)
        ]:
            subset = self.df[condition]
            status_data.append({
                'Payment Status': status,
                'Count': len(subset),
                'Total Amount': subset['total'].sum(),
                'Avg Amount': subset['total'].mean(),
                'Percentage %': (len(subset) / len(self.df) * 100)
            })

        return pd.DataFrame(status_data).round(2)

    def get_collection_rate(self):
        """Calculate overall collection rate"""
        total_due = self.df['total'].sum()
        total_paid = self.df['paid_amount'].sum()
        outstanding = self.df['remaining_balance'].sum()

        return {
            'Total Due': total_due,
            'Total Paid': total_paid,
            'Outstanding': outstanding,
            'Collection Rate %': (total_paid / (total_paid + outstanding) * 100),
            'Outstanding Rate %': (outstanding / (total_paid + outstanding) * 100)
        }

    def get_collection_by_size(self):
        """Analyze collection rate by transaction size"""
        ranges = [(0, 5000), (5000, 10000), (10000, 20000), (20000, 50000), (50000, 100000), (100000, float('inf'))]
        labels = ['0-5K', '5-10K', '10-20K', '20-50K', '50-100K', '100K+']

        analysis = []
        for (min_val, max_val), label in zip(ranges, labels):
            subset = self.df[(self.df['total'] >= min_val) & (self.df['total'] < max_val)]
            if len(subset) > 0:
                analysis.append({
                    'Size Range': label,
                    'Transactions': len(subset),
                    'Total Amount': subset['total'].sum(),
                    'Amount Paid': subset['paid_amount'].sum(),
                    'Outstanding': subset['remaining_balance'].sum(),
                    'Collection Rate %': (subset['paid_amount'].sum() /
                                        (subset['paid_amount'].sum() + subset['remaining_balance'].sum()) * 100)
                })

        return pd.DataFrame(analysis).round(2)

    def get_outstanding_customers(self):
        """Get customers with outstanding balances"""
        outstanding = self.df[self.df['remaining_balance'] > 0].groupby('customer_name').agg({
            'remaining_balance': 'sum',
            'total': 'sum',
            'paid_amount': 'sum',
            'id': 'count'
        }).reset_index()

        outstanding.columns = ['Customer', 'Outstanding', 'Total Due', 'Paid', 'Invoice Count']
        outstanding['Collection %'] = (outstanding['Paid'] / outstanding['Total Due'] * 100).round(2)
        return outstanding.sort_values('Outstanding', ascending=False)

# =============================================================================
# CLASS 5: DISCOUNT ANALYZER - Analyzes discount strategy
# =============================================================================

class DiscountAnalyzer:
    """Analyze discount metrics and impact"""

    def __init__(self, df):
        self.df = df

    def get_discount_summary(self):
        """Overall discount analysis"""
        discounted = self.df[self.df['discount_amount'] > 0]

        return {
            'Total Discounts': self.df['discount_amount'].sum(),
            'Avg Discount Amount': discounted['discount_amount'].mean() if len(discounted) > 0 else 0,
            'Max Discount': self.df['discount_amount'].max(),
            'Transactions with Discount': len(discounted),
            'Percentage of Transactions %': (len(discounted) / len(self.df) * 100),
            'Avg Discount %': discounted['discount_percentage'].mean() if len(discounted) > 0 else 0,
            'Discount as % of Revenue': (self.df['discount_amount'].sum() /
                                        self.df['total_before_discount'].sum() * 100)
        }

    def get_discount_distribution(self):
        """Distribution of discount percentages"""
        ranges = [(0, 0.1), (0.1, 0.5), (0.5, 1), (1, 1.5), (1.5, 100)]
        labels = ['0-0.1%', '0.1-0.5%', '0.5-1%', '1-1.5%', '1.5%+']

        distribution = []
        for (min_disc, max_disc), label in zip(ranges, labels):
            subset = self.df[(self.df['discount_percentage'] >= min_disc) &
                            (self.df['discount_percentage'] < max_disc)]
            if len(subset) > 0:
                distribution.append({
                    'Discount Range %': label,
                    'Transactions': len(subset),
                    'Avg Value': subset['total'].mean(),
                    'Avg Collection Rate %': (subset['paid_amount'].sum() /
                                            (subset['paid_amount'].sum() + subset['remaining_balance'].sum()) * 100)
                })

        return pd.DataFrame(distribution).round(2)

    def get_discount_impact(self):
        """Impact of discounting on revenue"""
        return {
            'Revenue Before Discount': self.df['total_before_discount'].sum(),
            'Total Discounts': self.df['discount_amount'].sum(),
            'Final Revenue': self.df['total'].sum(),
            'Discount Impact %': (self.df['discount_amount'].sum() /
                                self.df['total_before_discount'].sum() * 100),
            'Lost Revenue': self.df['total_before_discount'].sum() - self.df['total'].sum()
        }

# =============================================================================
# CLASS 6: STATISTICS ANALYZER - Statistical analysis and insights
# =============================================================================

class StatisticsAnalyzer:
    """Perform statistical analysis"""

    def __init__(self, df):
        self.df = df

    def get_descriptive_stats(self):
        """Calculate descriptive statistics"""
        stats = {
            'Count': len(self.df),
            'Mean': self.df['total'].mean(),
            'Median': self.df['total'].median(),
            'Std Dev': self.df['total'].std(),
            'Min': self.df['total'].min(),
            'Q1 (25%)': self.df['total'].quantile(0.25),
            'Q3 (75%)': self.df['total'].quantile(0.75),
            'Max': self.df['total'].max(),
            'Range': self.df['total'].max() - self.df['total'].min(),
            'IQR': self.df['total'].quantile(0.75) - self.df['total'].quantile(0.25)
        }
        return {k: round(v, 2) for k, v in stats.items()}

    def get_distribution_metrics(self):
        """Calculate distribution shape metrics"""
        return {
            'Skewness': round(self.df['total'].skew(), 4),
            'Kurtosis': round(self.df['total'].kurtosis(), 4),
            'Coefficient of Variation %': round(
                (self.df['total'].std() / self.df['total'].mean() * 100), 2
            ),
            'Variance': round(self.df['total'].var(), 2)
        }

    def get_percentiles(self):
        """Calculate percentile values"""
        percentiles = [10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 99]
        return {
            f'P{p}': round(self.df['total'].quantile(p/100), 2)
            for p in percentiles
        }

    def get_correlations(self):
        """Calculate key correlations"""
        return {
            'Items vs Transaction Value': round(
                self.df['items_count'].corr(self.df['total']), 4
            ),
            'Discount % vs Collection Rate': round(
                self.df['discount_percentage'].corr(self.df['payment_rate']), 4
            ),
            'Transaction Size vs Collection Rate': round(
                self.df['total'].corr(self.df['payment_rate']), 4
            )
        }

# =============================================================================
# MAIN ANALYSIS RUNNER
# =============================================================================

def run_complete_analysis(filepath):
    """Execute complete analysis pipeline"""

    print("\n" + "="*80)
    print("MEDICAL SALES DATA ANALYSIS - COMPLETE PIPELINE")
    print("="*80 + "\n")

    # Step 1: Load Data
    print("Step 1: Loading Data...")
    loader = DataLoader(filepath)
    df = loader.get_data()

    # Step 2: Revenue Analysis
    print("\nStep 2: Revenue Analysis...")
    revenue = RevenueAnalyzer(df)
    revenue_summary = revenue.get_summary()
    print(f"  Total Revenue: {revenue_summary['total_revenue']:,.2f}")
    print(f"  Avg Transaction: {revenue_summary['avg_transaction']:,.2f}")
    print(f"  Transactions: {len(df):,}")

    # Step 3: Customer Analysis
    print("\nStep 3: Customer Analysis...")
    customer = CustomerAnalyzer(df)
    segment_summary = customer.get_segment_summary()
    print(f"  Total Customers: {len(customer.customer_data):,}")
    print(segment_summary)

    # Step 4: Payment Analysis
    print("\nStep 4: Payment Analysis...")
    payment = PaymentAnalyzer(df)
    collection = payment.get_collection_rate()
    print(f"  Collection Rate: {collection['Collection Rate %']:.2f}%")
    print(f"  Outstanding Balance: {collection['Outstanding']:,.2f}")

    # Step 5: Discount Analysis
    print("\nStep 5: Discount Analysis...")
    discount = DiscountAnalyzer(df)
    discount_summary = discount.get_discount_summary()
    print(f"  Total Discounts: {discount_summary['Total Discounts']:,.2f}")
    print(f"  Discount % of Revenue: {discount_summary['Discount as % of Revenue']:.2f}%")

    # Step 6: Statistical Analysis
    print("\nStep 6: Statistical Analysis...")
    stats = StatisticsAnalyzer(df)
    descriptive = stats.get_descriptive_stats()
    print(f"  Mean: {descriptive['Mean']:,.2f}")
    print(f"  Median: {descriptive['Median']:,.2f}")
    print(f"  Std Dev: {descriptive['Std Dev']:,.2f}")

    print("\n" + "="*80)
    print("✓ ANALYSIS COMPLETE")
    print("="*80)

    return {
        'loader': loader,
        'revenue': revenue,
        'customer': customer,
        'payment': payment,
        'discount': discount,
        'stats': stats
    }

# =============================================================================
# EXECUTION
# =============================================================================

if __name__ == "__main__":
    # Run analysis
    results = run_complete_analysis('/mnt/user-data/uploads/final_cleaned_data.xlsx')

    # Export results to Excel (optional - would need additional code for this)
    print("\n✓ Use the analyzer objects for further analysis and exporting")